### PR TITLE
Leader board page

### PR DESCRIPTION
**Pull request by Wijantra**
Please review the leader board page.

image

### CODE REVIEW

**Comment by NutthanichN** [comment]
A fixed-header size is too big, can you adjust it?

**Comment by Wijantra** [comment]
> 
> 
> A fixed-header size is too big, can you adjust it?

Ok I will adjust the size of fixed-header.

**Comment by Wijantra** [comment]
> 
> 
> A fixed-header size is too big, can you adjust it?

I already adjust the size of fixed header.

image

**Comment by NutthanichN** [comment]
Seems like you adjust table header's size too. Everything is looking good now.

**Pull request merged**
