### PR TITLE
Leaderboard index

### PR DESCRIPTION
**Pull request by theethaj**
add leaderboard-index, please review
image
image

### CODE REVIEW

**Comment by NutthanichN** [comment]
This page has lot of static files, are all of these necessary?

**Comment by theethaj** [comment]
> It is what happens
> 
> image
> 
> Please check if you correctly import static files on html page. I think this happens because you use a wrong path to import static files (wrong folder name maybe?).

I already connect to the correct path.

**Comment by theethaj** [comment]
> This page has lot of static files, are all of these necessary?

I already delete an unnecessary items

**Comment by theethaj** [comment]
This branch is improved already. Please review again.

**Comment by NutthanichN** [comment]
Anyway, this page displays correctly now.

**Comment by Wijantra** [comment]
This page displays like your picture.
Good but i agree with @NutthanichN about prepros-6.config

**Comment by Wijantra** [comment]
And I should recommend you to use only leaderboard-index.html because  leaderboard-index.htmland leaderboard_index_after_login.html are the same except the fixed header. But it's just my recommend.

**Comment by theethaj** [comment]
> There is `prepros-6.config` in `templates` folder. What is this file? Do you use it to do something for this page? If you use it, please move it to `static` folder (and to the right sub-folder also). If not, please delete it from `templates` folder.
I remove `prepros-6.config` already.

**Comment by theethaj** [comment]
> There is `prepros-6.config` in `templates` folder. What is this file? Do you use it to do something for this page? If you use it, please move it to `static` folder (and to the right sub-folder also). If not, please delete it from `templates` folder.

I already remove `prepros-6.config` .

**Comment by theethaj** [comment]
This branch is improved already. Please review again.

**Comment by NutthanichN** [comment]
> 
> 
> And I should recommend you to use only leaderboard-index.html because leaderboard-index.htmland leaderboard_index_after_login.html are the same except the fixed header. But it's just my recommend.

I agree with @Wijantra I suggest you putting fixed header of `leaderboard_index_after_login.html` in `leaderboard-index.html` and comment that fixed header out and delete `leaderboard_index_after_login.html`, so everything about leaderboard is in one file (we can handle how to display it later).

**Comment by theethaj** [comment]
> > And I should recommend you to use only leaderboard-index.html because leaderboard-index.htmland leaderboard_index_after_login.html are the same except the fixed header. But it's just my recommend.
> 
> I agree with @Wijantra I suggest you putting fixed header of `leaderboard_index_after_login.html` in `leaderboard-index.html` and comment that fixed header out and delete `leaderboard_index_after_login.html`, so everything about leaderboard is in one file (we can handle how to display it later).

I already delete `leaderboard_index_after_login.html` and update `leaderboard-index.html`

**Comment by theethaj** [comment]
This branch is improved already. Please review again.

**Pull request merged**
