### PR TITLE
404-not-found

### PR DESCRIPTION
**Pull request by theethaj**
add 404-not-found page, please review.
image

### CODE REVIEW

**Comment by NutthanichN** [comment]
> 
> 
> Do you use all of these file??

Same question. All these static files scare me.

**Comment by theethaj** [comment]
> It displays like this in my laptop:
> 
> image
> 
> Can you check if you import static files on html file correctly?

already improve

**Comment by theethaj** [comment]
> > Do you use all of these file??
> 
> Same question. All these static files scare me.

already delete unnecessary items.

**Comment by theethaj** [comment]
> Do you use all of these file??

already delete unnecessary items

**Comment by theethaj** [comment]
> What does _flation.scss do?

It's not used. I already remove an unnecessary items.

**Comment by theethaj** [comment]
this branch is improved already. Please review again.

**Comment by Wijantra** [comment]
I agree with @NutthanichN about folder of prepros-6.config

**Comment by theethaj** [comment]
> This page displays correctly now, but please put `prepros-6.config` to the right folder if you use it.

I already remove `prepros-6.config`.

**Comment by theethaj** [comment]
This branch is improved already. Please review again.

**Pull request merged**
