### PR TITLE
Add social django auth

### PR DESCRIPTION
**Pull request by Wijantra**
I create social django auth for register user.
Register user can access `create-question.html`,` edit-question-set.html` but normal player can not access these pages if normal player try to access these page it will redirect to `login_result.html` .
 
And the fixed header will display login with google button when users does not login but when user login, the fixed header will display email, log out button and create quiz button.

**How to run**
` pip install -r requirements.txt`

`python manage.py migrate`

you must create *OAUTH2_KEY* and *OAUTH2_SECRET* in .env from  [this tutorial](https://developers.google.com/adwords/api/docs/guides/authentication) or ask me.

But now when user log out and login again, it doesn't display the login with google because it remember the email of register user. I try to fix but it does not work

### CODE REVIEW

**Comment by Wijantra** [comment]
I create base.css and reduce duplicate code on create-question.css,  edit-question-set.css, leaderboard.css and main.css.

And I check user.is_authenticated on template create-question.html, edit-question-set.html, index.html, leaderboard-index.html and leaderboard.html for display mashead

**Comment by NutthanichN** [comment]
image
Should it look like this when the user try to access create-quiz by url?

**Comment by NutthanichN** [comment]
> 
> 
> image
> Should it look like this when the user try to access create-quiz by url?

But those buttons work fine so I think it's not a big problem.

**Comment by Wijantra** [comment]
> 
> 
> Ok to use (we'll worry about page styling later)

I already fix it

**Pull request merged**
