### PR TITLE
player-name page

### PR DESCRIPTION
**Pull request by theethaj**
Add player-name page, please review.
image

### CODE REVIEW

**Comment by NutthanichN** [comment]
The repository **already** has `player-name.html`, why you still add `player_name.html` (with a wrong name convention for html)?

**Comment by theethaj** [comment]
> The repository **already** has `player-name.html`, why you still add `player_name.html` (with a wrong name convention for html)?

I already delete `player-name.html`

**Comment by theethaj** [comment]
> This happens
> 
> image
> 
> Please check if you import static files on html page correctly.

I already connect to the correct path.

**Comment by theethaj** [comment]
This branch is improved already. Please review again.

**Comment by Wijantra** [comment]
The page displays correctly. Good

**Comment by theethaj** [comment]
> It displays correctly now, but please change a file name from `player_name.html` to `player-name.html` (since every template uses `-`).

already edit file name to `player-name.html`

**Comment by theethaj** [comment]
> Do you use all of these files?
> I'm not sure but i see the file that you don't use in player_name.html

I'm sure, I use it.

**Comment by theethaj** [comment]
This branch is improved already. Please review again.

**Comment by Wijantra** [comment]
> 
> 
> > Do you use all of these files?
> > I'm not sure but i see the file that you don't use in player_name.html
> 
> I'm sure, I use it.

Ok

**Pull request merged**
