### PR TITLE
Index page

### PR DESCRIPTION
**Pull request by theethaj**
add index pages (before and after login), please review.
image
image
image
image

### CODE REVIEW

**Comment by NutthanichN** [comment]
I still have a question about this lot of static files, are all these files really necessary?

**Comment by theethaj** [comment]
> It displays like this in my laptop
> 
> image
> 
> I think it's a problem about import static files on html page. Can you check if you correctly import all static files?

I already connect to the correct path.

**Comment by theethaj** [comment]
> I still have a question about this lot of static files, are all these files really necessary?

I already delete an unnecessary items.

**Comment by theethaj** [comment]
This branch is improved already. Please review again.

**Comment by Wijantra** [comment]
I should recommend you to use only index.html because index.html and index_after_login.html are the same except the fixed header. But it's just my recommend.

**Comment by theethaj** [comment]
> This page works correctly now, but please put `prepros-6.config` to the right folder if you use it.

I already remove `prepros-6.config`.

**Comment by theethaj** [comment]
This branch is improved already. Please review again.

**Comment by NutthanichN** [comment]
> 
> 
> I should recommend you to use only index.html because index.html and index_after_login.html are the same except the fixed header. But it's just my recommend.

I agree with @Wijantra I suggest putting only fixed header of `index_after_login.html` to `index.html` then comment that fixed header out and delete `index_after_login.html`, so everything about index will be in one file (we can handle how to display it later).

**Comment by theethaj** [comment]
> > I should recommend you to use only index.html because index.html and index_after_login.html are the same except the fixed header. But it's just my recommend.
> 
> I agree with @Wijantra I suggest putting only fixed header of `index_after_login.html` to `index.html` then comment that fixed header out and delete `index_after_login.html`, so everything about index will be in one file (we can handle how to display it later).

I already collapse both files as `index.html`.

**Comment by theethaj** [comment]
This branch is improved already. Please review again.

**Pull request merged**
