### PR TITLE
question-level page

### PR DESCRIPTION
**Pull request by theethaj**
add question-level page, please review.
image

### CODE REVIEW

**Comment by theethaj** [comment]
> Which html file did you add a template code? I checked in `question-level.html` and found nothing.
> (From your preview picture I assume that you created a new file named `question_level.html` and didn't add to a repository if it's true please move your code to `question-level.html` provided from the master branch and check if you use the **correct** path to import static files)

I already connect to the correct path.

**Comment by theethaj** [comment]
This branch is improved already. Please review again.

**Comment by Wijantra** [comment]
This page displays like your picture when i run it in my labtop.
Good

**Comment by theethaj** [comment]
> I just see that there is `question_level.html` in the project root folder (thanks to @Wijantra). Please delete it since you already have the same one in `templates` folder, and we use html files from this folder only. And please change file name from `question_level.html` to `question-level.html` (to match other templates name).

I already rename it and delete `question_level.html` in the project root folder.

**Comment by theethaj** [comment]
This path is improved already. Please review again.

**Pull request merged**
