### PR TITLE
Login page

### PR DESCRIPTION
**Pull request by theethaj**
add login page, please review.
image

### CODE REVIEW

**Comment by NutthanichN** [comment]
Also have many static files, are these all necessary for this page?

**Comment by theethaj** [comment]
> This happens
> 
> image
> 
> There must be a problem about importing static files on html page. Please check if you use the correct path.

I already connect to the correct path.

**Comment by theethaj** [comment]
> Also have many static files, are these all necessary for this page?

already delete unnecessary items

**Comment by theethaj** [comment]
> There are many file.
> Do you use all of these file.

already delete unnecessary items

**Comment by theethaj** [comment]
This branch is improved already. Please review again.

**Comment by Wijantra** [comment]
This page displays like your picture.

**Pull request merged**
