### PR TITLE
result-page(s)

### PR DESCRIPTION
**Pull request by theethaj**
add result pages (winner and loser), please review.
image
image

### CODE REVIEW

**Comment by NutthanichN** [comment]
Page's style and layout are looking good but I just have some question. Why this page contains so many static files? Are all these files necessary?

**Comment by theethaj** [comment]
> Can you add home button on congratulation page too? So a player can go back to the index page.

I already add it.

**Comment by theethaj** [comment]
> Page's style and layout are looking good but I just have some question. Why this page contains so many static files? Are all these files necessary?
I already delete an unnecessary items

**Comment by theethaj** [comment]
> I think like @NutthanichN
> Could you add button to link to index page.

I already add it.

**Comment by theethaj** [comment]
> There are many files
> Do you use all of these files?

I already delete an unnecessary items.

**Comment by theethaj** [comment]
This branch is improved already. Please review again.

**Comment by NutthanichN** [comment]
Also, I think there must be some way to use only one `result.html`. Since `result_try_harder.html` and `result_congrats.html` only have different text (and button position).

**Comment by Wijantra** [comment]
I agree with @NutthanichN , it should has only result.html

**Comment by theethaj** [comment]
> There is `prepros-6.config` in `templates` folder. What is this file? Do you use it to do something for this page? If you use it, please move it to `static` folder (and to the right sub-folder also). If not, please delete it from `templates` folder.

already remove `prepros-6.config`

**Comment by theethaj** [comment]
> Also, I think there must be some way to use only one `result.html`. Since `result_try_harder.html` and `result_congrats.html` only have different text (and button position).

already collapse as result.html

**Comment by theethaj** [comment]
> I agree with @NutthanichN , it should has only result.html

already collapse as result.html

**Comment by theethaj** [comment]
This branch is improved already. Please review again.

**Pull request merged**
